/**
 * cognee-types — the dataset-name helpers that form the TENANT ISOLATION BOUNDARY inside cognee.
 *
 * `datasetFor()` / `kbDatasetFor()` had no test file of their own, and every test that touched them
 * mocked them (`cognee-memory.test.ts` stubs `datasetFor: () => 'org:acme'`). So the functions that
 * actually build the dataset name had never executed, while the module's own comment states the
 * property they exist to guarantee: "Falls back to a dead name with no org context so a caller that
 * forgot enterWithOrg reads and writes nothing instead of the shared 'default'."
 *
 * In `postgres` mode several orgs can share one cognee database, so the dataset name IS the boundary
 * — a wrong name is a cross-tenant memory leak, not a cosmetic bug.
 */
import { describe, expect, test, afterEach } from 'bun:test'
import { enterWithOrg, bypassOrg } from './prisma-tenant'
import { datasetFor, kbDatasetFor, isValidSearchType, COGNEE_SEARCH_TYPES } from './cognee-types'

afterEach(async () => {
  // Leave no org context behind for the next test in this file.
  await bypassOrg(async () => {})
})

describe('datasetFor — the per-org chat-memory dataset', () => {
  test('is prefixed with org: and carries the org id', async () => {
    await bypassOrg(async () => {
      enterWithOrg('acme')
      expect(datasetFor()).toBe('org:acme')
    })
  })

  test('TWO DIFFERENT ORGS get different dataset names', async () => {
    // The property that makes this an isolation boundary. If the org id were dropped from the name,
    // two orgs would read and write the SAME dataset and memory would bleed across customers.
    let a = ''
    let b = ''
    await bypassOrg(async () => {
      enterWithOrg('org-a')
      a = datasetFor()
    })
    await bypassOrg(async () => {
      enterWithOrg('org-b')
      b = datasetFor()
    })
    expect(a).not.toBe(b)
    expect(a).toBe('org:org-a')
    expect(b).toBe('org:org-b')
  })

  test('with NO org context it returns a DEAD name, never the shared "default"', async () => {
    // The fail-closed branch. 'default' is the name cognee falls back to on its own, so resolving to
    // it on a forgotten enterWithOrg would silently join every org's memory together. 'no-org'
    // matches no real org, so such a call is a no-op instead of a leak.
    const name = await bypassOrg(async () => datasetFor())
    expect(name).toBe('org:no-org')
    expect(name).not.toBe('default')
    expect(name).not.toContain('org-default')
  })

  test('the name is stable across repeated calls in one context', async () => {
    await bypassOrg(async () => {
      enterWithOrg('acme')
      expect(datasetFor()).toBe(datasetFor())
    })
  })
})

describe('kbDatasetFor — the per-org knowledge-graph dataset', () => {
  test('is the chat dataset with a :kb suffix', async () => {
    await bypassOrg(async () => {
      enterWithOrg('acme')
      expect(kbDatasetFor()).toBe('org:acme:kb')
      // The knowledge graph must NOT share a dataset with chat memory: cognify writes graph
    // entities into its dataset, and mixing them with raw chat turns pollutes graph recall.
      expect(kbDatasetFor()).not.toBe(datasetFor())
    })
  })

  test('with NO org context it also fails closed', async () => {
    const name = await bypassOrg(async () => kbDatasetFor())
    expect(name).toBe('org:no-org:kb')
    expect(name).not.toContain('default')
  })

  test('two orgs get different knowledge-graph datasets', async () => {
    let a = ''
    let b = ''
    await bypassOrg(async () => {
      enterWithOrg('org-a')
      a = kbDatasetFor()
    })
    await bypassOrg(async () => {
      enterWithOrg('org-b')
      b = kbDatasetFor()
    })
    expect(a).toBe('org:org-a:kb')
    expect(b).toBe('org:org-b:kb')
  })

  test('an org whose id contains a colon does not collide with the kb namespace', async () => {
    // Documents actual behaviour rather than asserting a sanitisation that does not exist: ids are
    // generated by us (cuid), so the suffix is unambiguous in practice. Pinned so a future change to
    // the format is a visible decision.
    await bypassOrg(async () => {
      enterWithOrg('acme')
      expect(datasetFor()).not.toBe(kbDatasetFor())
    })
  })
})

describe('isValidSearchType — the SDK literal guard', () => {
  test('accepts the literals the module lists', () => {
    for (const t of COGNEE_SEARCH_TYPES) expect(isValidSearchType(t)).toBe(true)
  })

  test('accepts SUMMARIES, CHUNKS and NATURAL_LANGUAGE specifically', () => {
    // These are the three the recall strategies actually use; a rename in the SDK would fail here
    // rather than remotely with "unknown SearchType".
    expect(isValidSearchType('SUMMARIES')).toBe(true)
    expect(isValidSearchType('CHUNKS')).toBe(true)
    expect(isValidSearchType('NATURAL_LANGUAGE')).toBe(true)
  })

  test('REJECTS the Python-only names that were once used here', () => {
    // GRAPH_ENTITIES / GRAPH_RELATIONSHIPS came from Python cognee docs and are not in the TS SDK
    // union; sending them wasted the whole retrieval strategy. See invariants.test.ts.
    expect(isValidSearchType('GRAPH_ENTITIES')).toBe(false)
    expect(isValidSearchType('GRAPH_RELATIONSHIPS')).toBe(false)
  })

  test('is case-SENSITIVE and rejects unknown or empty values', () => {
    expect(isValidSearchType('summaries')).toBe(false)
    expect(isValidSearchType('')).toBe(false)
    expect(isValidSearchType('NOPE')).toBe(false)
  })
})
