import { describe, expect, test, mock, beforeEach } from 'bun:test'

// --- DB mock (must precede import) ---
const mockExecuteRawUnsafe = mock<(sql: string, ...params: unknown[]) => Promise<number>>(async () => 1)
const mockQueryRawUnsafe = mock(
  async (sql: string, ..._params: unknown[]): Promise<unknown[]> => {
    if (sql.includes('PRAGMA')) {
      return [
        { name: 'id', type: 'INTEGER', notnull: 1, pk: 1 },
        { name: 'name', type: 'TEXT', notnull: 0, pk: 0 },
      ]
    }
    if (sql.includes('COUNT(*)')) return [{ c: 5 }]
    if (sql.includes('DISTINCT')) return [{ v: 'active' }, { v: 'pending' }]
    if (sql.includes('LIMIT 1')) return [{ id: 1, name: 'sample' }]
    return []
  },
)
const mockQueryRaw = mock(
  async (_strings: TemplateStringsArray, ..._values: unknown[]): Promise<unknown[]> => [{ c: 1 }],
)

mock.module('@/lib/db', () => ({
  db: {
    $executeRawUnsafe: mockExecuteRawUnsafe,
    $queryRawUnsafe: mockQueryRawUnsafe,
    $queryRaw: mockQueryRaw,
  },
}))
mock.module('@/lib/db-provider', () => ({ getDbProvider: () => 'sqlite' as const }))

import {
  describeSchema,
  type ReflectedTable,
  SqliteDemoConnector,
  ConnectorRegistry,
} from './connectors'

beforeEach(() => {
  mockExecuteRawUnsafe.mockClear()
  mockQueryRawUnsafe.mockClear()
  mockQueryRaw.mockClear()
})

describe('describeSchema', () => {
  test('renders PK, NOT NULL, FK, and distinct values', () => {
    const tables: ReflectedTable[] = [
      {
        tableName: 'orders',
        rowCount: 100,
        columns: [
          { name: 'id', type: 'INTEGER', primaryKey: true, notNull: true },
          { name: 'customer_id', type: 'INTEGER', notNull: true, foreignKey: 'customers.id' },
          { name: 'status', type: 'TEXT', distinctValues: ['pending', 'paid', 'shipped'] },
          { name: 'total', type: 'REAL' },
        ],
      },
    ]

    const out = describeSchema(tables)
    expect(out).toContain('PK: id')
    expect(out).toContain('id INTEGER PRIMARY KEY')
    expect(out).toContain('customer_id INTEGER NOT NULL -> customers.id')
    expect(out).toContain('status TEXT  -- values: pending, paid, shipped')
    expect(out).toContain('total REAL')
  })

  test('omits PK label when no primary key', () => {
    const tables: ReflectedTable[] = [
      {
        tableName: 'view_x',
        rowCount: 5,
        columns: [
          { name: 'a', type: 'TEXT' },
          { name: 'b', type: 'INTEGER' },
        ],
      },
    ]
    const out = describeSchema(tables)
    expect(out).not.toContain('PK:')
    expect(out).toContain('a TEXT')
    expect(out).toContain('b INTEGER')
  })

  test('renders sample row as comment', () => {
    const tables: ReflectedTable[] = [
      {
        tableName: 'orders',
        rowCount: 10,
        columns: [
          { name: 'id', type: 'INTEGER', primaryKey: true },
          { name: 'status', type: 'TEXT' },
          { name: 'total', type: 'REAL' },
        ],
        sampleRow: { id: 1001, status: 'delivered', total: 18500000 },
      },
    ]
    const out = describeSchema(tables)
    expect(out).toContain("-- sample: id=1001, status='delivered', total=18500000")
  })

  test('truncates long string values in sample row', () => {
    const longStr = 'A'.repeat(50)
    const tables: ReflectedTable[] = [
      {
        tableName: 't',
        rowCount: 1,
        columns: [{ name: 'desc', type: 'TEXT' }],
        sampleRow: { desc: longStr },
      },
    ]
    const out = describeSchema(tables)
    expect(out).toContain("desc='AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...'")
    expect(out).not.toContain(longStr + "'")
  })
})

// DDL test runs before fetch/execute tests so _bootstrapped is still false.
describe('SqliteDemoConnector — DDL generation (SQLite)', () => {
  test('ensureDemoSchema uses AUTOINCREMENT, not GENERATED BY DEFAULT AS IDENTITY', async () => {
    const c = new SqliteDemoConnector({})
    await c.testConnection()
    const sqls = mockExecuteRawUnsafe.mock.calls.map((call) => call[0] as string)
    const autoInc = sqls.find((s) => s.includes('AUTOINCREMENT'))
    expect(autoInc).toBeDefined()
    expect(sqls.some((s) => s.includes('GENERATED BY DEFAULT AS IDENTITY'))).toBe(false)
  })
})

describe('SqliteDemoConnector.fetchSchema (SQLite path)', () => {
  test('reflects 8 demo tables with columns from PRAGMA table_info', async () => {
    const c = new SqliteDemoConnector({})
    const schema = await c.fetchSchema()
    expect(schema).toHaveLength(8)
    expect(schema[0].tableName).toBe('demo_warehouses')
    const col = schema[0].columns.find((x) => x.name === 'id')
    expect(col?.primaryKey).toBe(true)
    const nameCol = schema[0].columns.find((x) => x.name === 'name')
    expect(nameCol?.notNull).toBe(false)
  })

  test('rowCount comes from COUNT(*) query', async () => {
    const c = new SqliteDemoConnector({})
    const schema = await c.fetchSchema()
    expect(schema[0].rowCount).toBe(5)
  })
})

describe('SqliteDemoConnector.executeQuery', () => {
  test('returns rows with rowCount and executionMs (happy path)', async () => {
    mockQueryRawUnsafe.mockImplementationOnce(async () => [{ id: 100, name: 'widget' }])
    const c = new SqliteDemoConnector({})
    const result = await c.executeQuery('SELECT * FROM demo_products LIMIT 1')
    expect(result.rowCount).toBe(1)
    expect(result.rows[0].id).toBe(100)
    expect(result.executionMs).toBeGreaterThanOrEqual(0)
  })

  test('rejects non-demo table via security allowlist', async () => {
    const c = new SqliteDemoConnector({})
    await expect(c.executeQuery('SELECT * FROM users')).rejects.toThrow('allowlist')
  })

  test('rejects JOIN to non-demo table', async () => {
    const c = new SqliteDemoConnector({})
    await expect(
      c.executeQuery('SELECT * FROM demo_products JOIN User ON 1=1'),
    ).rejects.toThrow()
  })
})

describe('ConnectorRegistry', () => {
  test('SQLITE_DEMO provider → SqliteDemoConnector instance', () => {
    const reg = new ConnectorRegistry()
    const c = reg.getConnector('i1', 'SQLITE_DEMO', {})
    expect(c.provider).toBe('SQLITE_DEMO')
  })

  test('POSTGRESQL provider → maps to demo connector (sandbox limitation)', () => {
    const reg = new ConnectorRegistry()
    const c = reg.getConnector('i2', 'POSTGRESQL', {})
    expect(c).toBeDefined()
    expect(c.provider).toBe('SQLITE_DEMO')
  })

  test('caches connector by integrationId (same instance)', () => {
    const reg = new ConnectorRegistry()
    const c1 = reg.getConnector('i3', 'SQLITE_DEMO', {})
    const c2 = reg.getConnector('i3', 'SQLITE_DEMO', {})
    expect(c1).toBe(c2)
  })

  test('drop removes cached connector (next call creates new instance)', () => {
    const reg = new ConnectorRegistry()
    const c1 = reg.getConnector('i4', 'SQLITE_DEMO', {})
    reg.drop('i4')
    const c2 = reg.getConnector('i4', 'SQLITE_DEMO', {})
    expect(c1).not.toBe(c2)
  })
})
