import { describe, expect, test, mock, beforeEach } from 'bun:test'

// --- Mocks: Postgres provider + DB (must precede import) ---
const mockExecuteRawUnsafe = mock<(sql: string, ...params: unknown[]) => Promise<number>>(async () => 1)
const mockQueryRawUnsafe = mock(
  async (sql: string, ..._params: unknown[]): Promise<unknown[]> => {
    if (sql.includes('information_schema.columns')) {
      return [
        { name: 'id', type: 'integer', notnull: 1, pk: 1 },
        { name: 'name', type: 'text', notnull: 0, pk: 0 },
      ]
    }
    if (sql.includes('COUNT(*)')) return [{ c: 3 }]
    if (sql.includes('DISTINCT')) return [{ v: 'x' }]
    if (sql.includes('LIMIT 1')) return [{ id: 1, name: 'pg-sample' }]
    return []
  },
)
const mockQueryRaw = mock(
  async (_strings: TemplateStringsArray, ..._values: unknown[]): Promise<unknown[]> => [{ c: 1 }],
)

mock.module('@/lib/db', () => ({
  db: {
    $executeRawUnsafe: mockExecuteRawUnsafe,
    $queryRawUnsafe: mockQueryRawUnsafe,
    $queryRaw: mockQueryRaw,
  },
}))
mock.module('@/lib/db-provider', () => ({ getDbProvider: () => 'postgresql' as const }))

import { SqliteDemoConnector, ConnectorRegistry } from './connectors'

beforeEach(() => {
  mockExecuteRawUnsafe.mockClear()
  mockQueryRawUnsafe.mockClear()
  mockQueryRaw.mockClear()
})

describe('SqliteDemoConnector — DDL generation (Postgres path)', () => {
  test('ensureDemoSchema uses GENERATED BY DEFAULT AS IDENTITY, not AUTOINCREMENT', async () => {
    const c = new SqliteDemoConnector({})
    await c.testConnection()
    const sqls = mockExecuteRawUnsafe.mock.calls.map((call) => call[0] as string)
    const identity = sqls.find((s) => s.includes('GENERATED BY DEFAULT AS IDENTITY'))
    expect(identity).toBeDefined()
    expect(sqls.some((s) => s.includes('AUTOINCREMENT'))).toBe(false)
  })
})

describe('SqliteDemoConnector.fetchSchema (Postgres path)', () => {
  test('queries information_schema.columns instead of PRAGMA', async () => {
    const c = new SqliteDemoConnector({})
    const schema = await c.fetchSchema()
    expect(schema).toHaveLength(8)
    const col = schema[0].columns.find((x) => x.name === 'id')
    expect(col?.primaryKey).toBe(true)
    // Verify the information_schema query was issued (not PRAGMA)
    const infoSchemaCalls = mockQueryRawUnsafe.mock.calls.filter((call) =>
      String(call[0]).includes('information_schema'),
    )
    expect(infoSchemaCalls.length).toBe(8)
  })

  test('rowCount from COUNT(*) on Postgres', async () => {
    const c = new SqliteDemoConnector({})
    const schema = await c.fetchSchema()
    expect(schema[0].rowCount).toBe(3)
  })
})

describe('ConnectorRegistry (Postgres)', () => {
  test('MYSQL family → demo connector (sandbox)', () => {
    const reg = new ConnectorRegistry()
    const c = reg.getConnector('pg1', 'MYSQL', {})
    expect(c).toBeDefined()
  })
})
