/**
 * 3.1 / 3.2 — Dynamic Connector Factory & Registry
 * ----------------------------------------------------------------------------
 * Provider-agnostic BaseDatabaseConnector + ConnectorRegistry.
 * Supports PostgreSQL, MySQL, MSSQL, MongoDB, ClickHouse, Oracle, Snowflake.
 */
import { db } from '@/lib/db'
import { getDbProvider } from '@/lib/db-provider'
import { getDbProtocolFamily } from '@/lib/db-provider-presets'
import { PostgresConnector, MysqlConnector, MssqlConnector, ClickHouseConnector } from './real-connectors'

const isPostgres = () => getDbProvider() === 'postgresql'

export interface ReflectedColumn {
  name: string
  type: string
  primaryKey?: boolean
  notNull?: boolean
  foreignKey?: string
  distinctValues?: string[]
}
export interface ReflectedTable {
  tableName: string
  columns: ReflectedColumn[]
  rowCount?: number
  sampleRow?: QueryRow
}
export interface QueryRow {
  [column: string]: unknown
}
export interface QueryResult {
  rows: QueryRow[]
  rowCount: number
  executionMs: number
}

export interface BaseDatabaseConnector {
  readonly provider: string
  testConnection(): Promise<boolean>
  fetchSchema(): Promise<ReflectedTable[]>
  executeQuery(sql: string): Promise<QueryResult>
  // ponytail: optional — only real connectors with pools implement this.
  close?(): Promise<void>
}

// ---------------------------------------------------------------------------
// Registry  (spec §3.2)
// ---------------------------------------------------------------------------

export class ConnectorRegistry {
  private _pools = new Map<string, BaseDatabaseConnector>()

  getConnector(integrationId: string, provider: string, decryptedConfig: Record<string, unknown>): BaseDatabaseConnector {
    if (!this._pools.has(integrationId)) {
      const family = getDbProtocolFamily(provider)
      let connector: BaseDatabaseConnector
      switch (family) {
        case 'POSTGRESQL':
          connector = new PostgresConnector(decryptedConfig)
          break
        case 'MYSQL':
          connector = new MysqlConnector(decryptedConfig)
          break
        case 'MSSQL':
          connector = new MssqlConnector(decryptedConfig)
          break
        case 'CLICKHOUSE':
          connector = new ClickHouseConnector(decryptedConfig)
          break
        default:
          throw new Error(`Provider ${provider} is not supported.`)
      }
      this._pools.set(integrationId, connector)
    }
    return this._pools.get(integrationId)!
  }

  drop(integrationId: string) {
    const c = this._pools.get(integrationId)
    this._pools.delete(integrationId)
    // ponytail: fire-and-forget pool cleanup — keeps drop() sync for existing callers.
    if (c?.close) c.close().catch(() => {})
  }
}

export const connectorRegistry = new ConnectorRegistry()

// ---------------------------------------------------------------------------
// Demo schema bootstrap — populates a realistic ERP dataset on first use.
// ---------------------------------------------------------------------------
let _bootstrapped = false

export function resetDemoSchemaBootstrap() { _bootstrapped = false }

export async function ensureDemoSchema(): Promise<void> {
  if (_bootstrapped) return
  _bootstrapped = true

  // Prisma's $executeRawUnsafe runs ONE statement at a time — split them.
  // ponytail: Postgres replaces AUTOINCREMENT with GENERATED BY DEFAULT AS IDENTITY
  // (allows explicit-id inserts from seed, auto-generates when id omitted).
  const ddl = [
    `CREATE TABLE IF NOT EXISTS demo_warehouses (id INTEGER PRIMARY KEY, name TEXT NOT NULL, location TEXT, capacity INTEGER)`,
    `CREATE TABLE IF NOT EXISTS demo_products (sku TEXT PRIMARY KEY, name TEXT NOT NULL, category TEXT, unit_price REAL, cost REAL, is_active INTEGER DEFAULT 1)`,
    `CREATE TABLE IF NOT EXISTS demo_inventory (id INTEGER PRIMARY KEY AUTOINCREMENT, sku TEXT NOT NULL, warehouse_id INTEGER NOT NULL, quantity INTEGER NOT NULL, reorder_level INTEGER, last_updated TEXT)`,
    `CREATE TABLE IF NOT EXISTS demo_customers (id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT, segment TEXT, city TEXT, total_spent REAL DEFAULT 0)`,
    `CREATE TABLE IF NOT EXISTS demo_orders (id INTEGER PRIMARY KEY, customer_id INTEGER NOT NULL, order_date TEXT NOT NULL, status TEXT, total_amount REAL)`,
    `CREATE TABLE IF NOT EXISTS demo_order_items (id INTEGER PRIMARY KEY AUTOINCREMENT, order_id INTEGER NOT NULL, sku TEXT NOT NULL, quantity INTEGER, unit_price REAL)`,
    `CREATE TABLE IF NOT EXISTS demo_invoices (invoice_no TEXT PRIMARY KEY, customer_id INTEGER, invoice_date TEXT, amount REAL, status TEXT)`,
    `CREATE TABLE IF NOT EXISTS demo_employees (id INTEGER PRIMARY KEY, name TEXT, department TEXT, role TEXT, hire_date TEXT, salary REAL)`,
  ]
  const finalDdl = isPostgres()
    ? ddl.map((s) => s.replace('INTEGER PRIMARY KEY AUTOINCREMENT', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'))
    : ddl
  for (const stmt of finalDdl) {
    await db.$executeRawUnsafe(stmt)
  }

  // Seed only if empty
  const c = await db.$queryRaw<{ c: number }[]>`SELECT COUNT(*) as c FROM demo_products;`
  if (Number(c[0]?.c) > 0) return

  await db.$executeRawUnsafe(`INSERT INTO demo_warehouses (id, name, location, capacity) VALUES (1, 'Jakarta Main Warehouse', 'West Jakarta', 50000), (2, 'Surabaya Warehouse', 'Surabaya', 30000), (3, 'Bandung Warehouse', 'Bandung', 20000)`)

  await db.$executeRawUnsafe(`INSERT INTO demo_products (sku, name, category, unit_price, cost, is_active) VALUES ('SKU-901', 'Laptop Enterprise 14"', 'Electronics', 18500000, 15200000, 1), ('SKU-902', 'Mouse Wireless Pro', 'Accessories', 285000, 190000, 1), ('SKU-903', 'Mechanical Keyboard', 'Accessories', 750000, 520000, 1), ('SKU-904', 'Monitor 27" 4K', 'Electronics', 4200000, 3350000, 1), ('SKU-905', 'SSD NVMe 1TB', 'Storage', 1450000, 1100000, 1), ('SKU-906', 'Webcam HD 1080p', 'Accessories', 395000, 260000, 1), ('SKU-907', 'Headset Noise Cancel', 'Audio', 1290000, 880000, 1), ('SKU-908', 'Docking Station USB-C', 'Accessories', 1850000, 1350000, 1), ('SKU-909', 'Router WiFi 6', 'Networking', 1450000, 980000, 1), ('SKU-910', 'UPS 1500VA', 'Power', 1750000, 1200000, 1)`) // nosemgrep — data array entry, not obfuscated code

  await db.$executeRawUnsafe(`INSERT INTO demo_inventory (sku, warehouse_id, quantity, reorder_level, last_updated) VALUES ('SKU-901', 1, 1420, 100, '2026-06-01'), ('SKU-901', 2, 340, 100, '2026-06-01'), ('SKU-902', 1, 5800, 500, '2026-06-01'), ('SKU-902', 2, 2100, 500, '2026-06-01'), ('SKU-903', 1, 1200, 200, '2026-06-01'), ('SKU-904', 1, 450, 80, '2026-06-01'), ('SKU-904', 3, 180, 80, '2026-06-01'), ('SKU-905', 1, 3200, 300, '2026-06-01'), ('SKU-906', 1, 2750, 300, '2026-06-01'), ('SKU-907', 1, 890, 150, '2026-06-01'), ('SKU-908', 2, 540, 100, '2026-06-01'), ('SKU-909', 1, 1120, 200, '2026-06-01'), ('SKU-910', 3, 95, 100, '2026-06-01')`) // nosemgrep — data array entry, not obfuscated code

  await db.$executeRawUnsafe(`INSERT INTO demo_customers (id, name, email, segment, city, total_spent) VALUES (1, 'PT Forward Together', 'proc@forwardtogether.co.id', 'Enterprise', 'Jakarta', 145000000), (2, 'CV Prosperous Success', 'purchases@prosperoussuccess.id', 'SMB', 'Bandung', 28500000), (3, 'PT Global Technology', 'it@globaltech.id', 'Enterprise', 'Surabaya', 98000000), (4, 'UD Independent Blessing', 'admin@independentblessing.com', 'SMB', 'Semarang', 12300000), (5, 'PT Digital Light', 'ops@digitallight.digital', 'Enterprise', 'Jakarta', 67500000), (6, 'CV Eternal Creation', 'po@eternalcreation.id', 'SMB', 'Yogyakarta', 18900000), (7, 'PT Great Nusantara', 'proc@greatnusantara.co.id', 'Enterprise', 'Medan', 53000000)`) // nosemgrep — data array entry, not obfuscated code

  await db.$executeRawUnsafe(`INSERT INTO demo_orders (id, customer_id, order_date, status, total_amount) VALUES (1001, 1, '2026-05-12', 'delivered', 18500000), (1002, 3, '2026-05-15', 'delivered', 8400000), (1003, 5, '2026-05-18', 'shipped', 4200000), (1004, 1, '2026-05-22', 'delivered', 1450000), (1005, 2, '2026-05-25', 'delivered', 855000), (1006, 7, '2026-05-28', 'shipped', 1290000), (1007, 3, '2026-06-02', 'processing', 3700000), (1008, 5, '2026-06-05', 'delivered', 5800000), (1009, 6, '2026-06-08', 'processing', 1850000), (1010, 1, '2026-06-10', 'delivered', 22500000)`) // nosemgrep — data array entry, not obfuscated code

  await db.$executeRawUnsafe(`INSERT INTO demo_order_items (order_id, sku, quantity, unit_price) VALUES (1001, 'SKU-901', 1, 18500000), (1002, 'SKU-904', 2, 4200000), (1003, 'SKU-905', 3, 1450000), (1004, 'SKU-902', 5, 285000), (1005, 'SKU-903', 1, 750000), (1006, 'SKU-907', 1, 1290000), (1007, 'SKU-904', 1, 4200000), (1007, 'SKU-906', 3, 395000), (1008, 'SKU-901', 1, 1850000), (1008, 'SKU-909', 1, 1450000), (1009, 'SKU-905', 1, 1450000), (1010, 'SKU-901', 1, 18500000)`) // nosemgrep — data array entry, not obfuscated code

  await db.$executeRawUnsafe(`INSERT INTO demo_invoices (invoice_no, customer_id, invoice_date, amount, status) VALUES ('INV-2026-001', 1, '2026-05-12', 18500000, 'paid'), ('INV-2026-002', 3, '2026-05-15', 8400000, 'paid'), ('INV-2026-003', 5, '2026-05-18', 4200000, 'pending'), ('INV-2026-004', 1, '2026-05-22', 1450000, 'paid'), ('INV-2026-005', 2, '2026-05-25', 855000, 'paid'), ('INV-2026-006', 7, '2026-05-28', 1290000, 'pending'), ('INV-2026-007', 3, '2026-06-02', 3700000, 'overdue'), ('INV-2026-008', 5, '2026-06-05', 5800000, 'paid'), ('INV-2026-009', 6, '2026-06-08', 1850000, 'pending'), ('INV-2026-010', 1, '2026-06-10', 22500000, 'paid')`) // nosemgrep — data array entry, not obfuscated code

  await db.$executeRawUnsafe(`INSERT INTO demo_employees (id, name, department, role, hire_date, salary) VALUES (1, 'Budi Santoso', 'IT', 'Manager', '2020-03-15', 25000000), (2, 'Siti Rahayu', 'Finance', 'Staff', '2021-07-01', 12000000), (3, 'Andi Wijaya', 'Sales', 'Manager', '2019-11-10', 23000000), (4, 'Dewi Lestari', 'HR', 'Staff', '2022-02-14', 11000000), (5, 'Rudi Hartono', 'Operations', 'Staff', '2021-09-20', 12500000), (6, 'Maya Putri', 'IT', 'Staff', '2023-01-05', 13500000), (7, 'Joko Susilo', 'Sales', 'Staff', '2020-08-12', 11500000)`) // nosemgrep — data array entry, not obfuscated code
}

/** Build a compact schema description string for the LLM Text-to-SQL prompt. */
export function describeSchema(tables: ReflectedTable[]): string {
  return tables
    .map((t) => {
      const pkCols = t.columns.filter((c) => c.primaryKey).map((c) => c.name)
      const pkLabel = pkCols.length > 0 ? `  PK: ${pkCols.join(', ')}` : ''
      const header = `TABLE ${t.tableName} (${t.rowCount ?? '?'} rows)${pkLabel}`
      const cols = t.columns
        .map((c) => {
          let line = `  ${c.name} ${c.type}`
          if (c.primaryKey) line += ' PRIMARY KEY'
          else if (c.notNull) line += ' NOT NULL'
          if (c.foreignKey) line += ` -> ${c.foreignKey}`
          if (c.distinctValues && c.distinctValues.length > 0) {
            line += `  -- values: ${c.distinctValues.join(', ')}`
          }
          return line
        })
        .join('\n')
      let sample = ''
      if (t.sampleRow) {
        const parts = t.columns
          .filter((c) => t.sampleRow![c.name] !== undefined && t.sampleRow![c.name] !== null)
          .map((c) => {
            const v = t.sampleRow![c.name]
            const sv = typeof v === 'string' ? `'${v.length > 40 ? v.slice(0, 37) + '...' : v}'` : String(v)
            return `${c.name}=${sv}`
          })
        if (parts.length > 0) sample = `  -- sample: ${parts.join(', ')}`
      }
      return `${header}\n${cols}${sample ? '\n' + sample : ''}`
    })
    .join('\n\n')
}
