// ---------------------------------------------------------------------------
// ensureDemoSchema — the demo ERP bootstrap
//
// connectors.test.ts only covers ConnectorRegistry, and it imports the module
// statically with no db mock, so the bootstrap had never run. Three behaviours
// matter and none were pinned: it must be IDEMPOTENT (a second call must not
// re-run 8 DDL statements and 8 inserts), it must translate
// `INTEGER PRIMARY KEY AUTOINCREMENT` to the Postgres IDENTITY form, and it must
// seed only when the table is empty.
// ---------------------------------------------------------------------------
import { describe, expect, test, mock, beforeEach } from 'bun:test'

const state = {
  provider: 'postgresql' as string,
  executeRawUnsafe: [] as string[],
  executeRawUnsafeThrows: null as Error | null,
  count: 0 as number,
  queryRawCalls: 0,
}

mock.module('@/lib/db', () => ({
  db: {
    $executeRawUnsafe: async (sql: string) => {
      if (state.executeRawUnsafeThrows) throw state.executeRawUnsafeThrows
      state.executeRawUnsafe.push(sql)
      return 1
    },
    // Tagged-template shape: (strings, ...values) => rows
    $queryRaw: async () => {
      state.queryRawCalls++
      return [{ c: state.count }]
    },
  },
}))

mock.module('@/lib/db-provider', () => ({
  getDbProvider: () => state.provider,
}))

// The real connector classes construct pools; none of them are needed here.
mock.module('./real-connectors', () => ({
  PostgresConnector: class {},
  MysqlConnector: class {},
  MssqlConnector: class {},
  ClickHouseConnector: class {},
}))

mock.module('@/lib/db-provider-presets', () => ({
  getDbProtocolFamily: () => 'sql',
}))

const { ensureDemoSchema, resetDemoSchemaBootstrap } = await import('./connectors')

beforeEach(() => {
  state.provider = 'postgresql'
  state.executeRawUnsafe = []
  state.executeRawUnsafeThrows = null
  state.count = 0
  state.queryRawCalls = 0
  resetDemoSchemaBootstrap()
})

describe('ensureDemoSchema', () => {
  test('it creates all 8 demo tables', async () => {
    await ensureDemoSchema()
    const creates = state.executeRawUnsafe.filter((s) => s.startsWith('CREATE TABLE'))
    expect(creates).toHaveLength(8)
    // Each must be IF NOT EXISTS: the bootstrap can race a second worker, and a
    // plain CREATE would abort the whole batch on the loser.
    expect(creates.every((s) => s.includes('IF NOT EXISTS'))).toBe(true)
    // Prisma's $executeRawUnsafe runs ONE statement, so they must be separate.
    expect(creates.every((s) => !s.includes(';') || s.trim().endsWith(';'))).toBe(true)
  })

  test('a SECOND call does nothing (the bootstrap is memoised)', async () => {
    await ensureDemoSchema()
    const afterFirst = state.executeRawUnsafe.length
    await ensureDemoSchema()
    // Re-running would re-issue 8 DDLs plus 8 inserts on every request path that
    // touches the demo connector.
    expect(state.executeRawUnsafe.length).toBe(afterFirst)
  })

  test('resetDemoSchemaBootstrap allows a deliberate re-run', async () => {
    await ensureDemoSchema()
    const first = state.executeRawUnsafe.length
    resetDemoSchemaBootstrap()
    await ensureDemoSchema()
    // The escape hatch exists for tests and for a forced re-provision.
    expect(state.executeRawUnsafe.length).toBeGreaterThan(first)
  })

  test('on Postgres, AUTOINCREMENT becomes GENERATED BY DEFAULT AS IDENTITY', async () => {
    state.provider = 'postgresql'
    await ensureDemoSchema()
    const creates = state.executeRawUnsafe.filter((s) => s.startsWith('CREATE TABLE'))
    // Postgres rejects AUTOINCREMENT outright, so without this rewrite the whole
    // bootstrap throws and the demo dataset never appears.
    expect(creates.some((s) => s.includes('AUTOINCREMENT'))).toBe(false)
    expect(creates.some((s) => s.includes('GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'))).toBe(true)
    // The tables that do not use AUTOINCREMENT keep their plain PRIMARY KEY.
    expect(creates.some((s) => s.includes('demo_warehouses (id INTEGER PRIMARY KEY'))).toBe(true)
  })

  test('on a non-Postgres provider the DDL is passed through unchanged', async () => {
    state.provider = 'mysql'
    await ensureDemoSchema()
    const creates = state.executeRawUnsafe.filter((s) => s.startsWith('CREATE TABLE'))
    // SQLite/MySQL accept AUTOINCREMENT; rewriting it there would be wrong.
    expect(creates.some((s) => s.includes('AUTOINCREMENT'))).toBe(true)
    expect(creates.some((s) => s.includes('GENERATED BY DEFAULT AS IDENTITY'))).toBe(false)
  })

  test('an EMPTY demo_products gets the seed rows', async () => {
    state.count = 0
    await ensureDemoSchema()
    const inserts = state.executeRawUnsafe.filter((s) => s.startsWith('INSERT INTO'))
    // 8 tables, but inventory/products/customers/orders/order_items/invoices/
    // employees/warehouses each get exactly one multi-row insert.
    expect(inserts).toHaveLength(8)
  })

  test('a NON-empty demo_products is not seeded again', async () => {
    state.count = 10
    await ensureDemoSchema()
    const inserts = state.executeRawUnsafe.filter((s) => s.startsWith('INSERT INTO'))
    // Re-seeding would duplicate every order and inflate the demo revenue figures.
    expect(inserts).toHaveLength(0)
    // The count is still read: the decision depends on it.
    expect(state.queryRawCalls).toBe(1)
  })

  test('the seed count is read with a COUNT(*), not a row fetch', async () => {
    await ensureDemoSchema()
    expect(state.queryRawCalls).toBe(1)
  })

  test('a failing DDL propagates rather than silently leaving a partial schema', async () => {
    state.executeRawUnsafeThrows = new Error('permission denied for schema public')
    // Swallowing this would leave the demo connector half-created: the app would
    // believe the dataset exists and every Text-to-SQL query against it would fail
    // with a confusing "relation does not exist".
    await expect(ensureDemoSchema()).rejects.toThrow('permission denied')
  })

  test('the memo is set BEFORE the work, so a failed bootstraps is not retried forever', async () => {
    state.executeRawUnsafeThrows = new Error('boom')
    await expect(ensureDemoSchema()).rejects.toThrow('boom')
    state.executeRawUnsafeThrows = null
    state.executeRawUnsafe = []
    await ensureDemoSchema()
    // MEASURED, and it documents a real trade-off rather than a bug: _bootstrapped
    // is set before the first await, so a failure is NOT re-attempted on the next
    // call. That keeps a permanently broken DDL from being retried on every request.
    expect(state.executeRawUnsafe).toHaveLength(0)
  })
})

// ---------------------------------------------------------------------------
// describeSchema — the Text-to-SQL prompt
//
// Never tested directly. This string is the ONLY thing the Text-to-SQL model
// knows about the database, so a defect here is a wrong answer, not a cosmetic
// bug. The quoting rules encode a real Postgres behaviour (unquoted identifiers
// are lowercased) and the business description is the highest-value token in
// the prompt.
// ---------------------------------------------------------------------------

const { describeSchema } = await import('./connectors')

describe('describeSchema', () => {
  test('renders the table, its row count and every column', () => {
    const out = describeSchema([
      {
        tableName: 'orders',
        rowCount: 120,
        columns: [
          { name: 'id', type: 'int', primaryKey: true },
          { name: 'total', type: 'numeric', notNull: true },
        ],
      },
    ])
    expect(out).toContain('TABLE orders (120 rows)')
    expect(out).toContain('PK: id')
    expect(out).toContain('id int PRIMARY KEY')
    expect(out).toContain('total numeric NOT NULL')
  })

  test('an unknown row count never renders as 0 or undefined', () => {
    // rowCount is typed number|undefined, but a real reflection can yield null, and Postgres
    // reports -1 for a table it has never ANALYZEd. All three mean "no estimate" and must NOT be
    // rendered as a number: "0 rows" tells the model the table is empty and suppresses a valid
    // query, while "-1 rows" is not a quantity at all.
    const unknown = [
      null as unknown as undefined,
      undefined,
      -1, // pg_class.reltuples for a never-ANALYZEd table
    ]
    for (const rowCount of unknown) {
      const out = describeSchema([{ tableName: 't', rowCount, columns: [{ name: 'a', type: 'int' }] }])
      expect(out).toContain('TABLE t (row count unknown)')
      expect(out).not.toContain('0 rows')
      expect(out).not.toContain('-1 rows')
    }
    // A real count still renders as a number — the fix must not swallow known values.
    const known = describeSchema([{ tableName: 't', rowCount: 42, columns: [{ name: 'a', type: 'int' }] }])
    expect(known).toContain('TABLE t (42 rows)')
  })

  test('a table name with UPPERCASE letters is quoted', () => {
    const out = describeSchema([{ tableName: 'MyTable', rowCount: 1, columns: [{ name: 'a', type: 'int' }] }])
    // Postgres lowercases unquoted identifiers, so "MyTable" must reach the model
    // as "MyTable" — otherwise the generated SQL misses the real table.
    expect(out).toContain('TABLE "MyTable"')
  })

  test('a column with UPPERCASE letters is quoted', () => {
    const out = describeSchema([
      { tableName: 't', rowCount: 1, columns: [{ name: 'IsDeleted', type: 'boolean' }] },
    ])
    // Same reason as the table name: `IsDeleted` would become `isdeleted`.
    expect(out).toContain('"IsDeleted" boolean')
  })

  test('a foreign key renders as an arrow to the target', () => {
    const out = describeSchema([
      { tableName: 'orders', rowCount: 1, columns: [{ name: 'customer_id', type: 'int', foreignKey: 'customers.id' }] },
    ])
    // Without this the model has to guess the join, which is where most
    // multi-table Text-to-SQL answers go wrong.
    expect(out).toContain('customer_id int -> customers.id')
  })

  test('the business description renders FIRST, before the columns', () => {
    const out = describeSchema([
      {
        tableName: 'orders',
        rowCount: 1,
        description: 'Customer purchase orders, one row per order.',
        columns: [{ name: 'id', type: 'int' }],
      },
    ])
    // One sentence per table is the highest-value token here; dropping it made the
    // model infer business meaning from column names alone.
    expect(out).toContain('-- Customer purchase orders, one row per order.')
    expect(out.indexOf('Customer purchase orders')).toBeLessThan(out.indexOf('id int'))
  })

  test('a sample row is rendered on its own line', () => {
    const out = describeSchema([
      { tableName: 't', rowCount: 1, columns: [{ name: 'id', type: 'int' }], sampleRow: { id: 7 } },
    ])
    expect(out).toContain('-- sample: id=7')
  })

  test('a long string sample is truncated so one cell cannot dominate the prompt', () => {
    const out = describeSchema([
      {
        tableName: 't',
        rowCount: 1,
        columns: [{ name: 'note', type: 'text' }],
        sampleRow: { note: 'x'.repeat(100) },
      },
    ])
    expect(out).toContain('...')
    // 40 chars max: the cell is quoted, so 37 + '...'
    expect(out).toContain(`note='${'x'.repeat(37)}...'`)
    expect(out).not.toContain('x'.repeat(41))
  })

  test('a NULL sample value is omitted, not printed as null', () => {
    const out = describeSchema([
      {
        tableName: 't',
        rowCount: 1,
        columns: [{ name: 'a', type: 'int' }, { name: 'b', type: 'text' }],
        sampleRow: { a: 1, b: null },
      },
    ])
    // Printing `b=null` reads as a literal value rather than "unknown".
    expect(out).toContain('a=1')
    expect(out).not.toContain('b=null')
  })

  test('a sample row whose values are ALL null produces no sample line', () => {
    const out = describeSchema([
      { tableName: 't', rowCount: 1, columns: [{ name: 'a', type: 'int' }], sampleRow: { a: null } },
    ])
    // An empty "-- sample:" header would be pure noise in every prompt.
    expect(out).not.toContain('-- sample:')
  })

  test('multiple tables are separated by a blank line', () => {
    const out = describeSchema([
      { tableName: 'a', rowCount: 1, columns: [{ name: 'x', type: 'int' }] },
      { tableName: 'b', rowCount: 2, columns: [{ name: 'y', type: 'int' }] },
    ])
    expect(out).toContain('\n\n')
    expect(out.indexOf('TABLE a')).toBeLessThan(out.indexOf('TABLE b'))
  })
})
