import { enterWithOrg } from '@/lib/prisma-tenant'
import { requireRole, writeAudit } from '@/lib/session'
/**
 * Spec §3.2 / §5.1 — Return cached reflected schema (tables + columns + rowCount).
 * ----------------------------------------------------------------------------
 * GET    /api/integrations/[id]/schema          — cached reflected schema (?refresh=1 re-reflects)
 * PATCH  /api/integrations/[id]/schema          — edit a table description (admin),
 *        locking it from re-enrichment via `manualDescription`. `{ description: null }`
 *        clears the lock + the description so the next enrichment regenerates it.
 *
 * Server-only route handler. No 'use client'.
 */
import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { getActiveUser, handleApiError } from '@/lib/session'
import { decryptConfig } from '@/lib/crypto'
import { connectorRegistry } from '@/lib/connectors'
import { invalidateSourceEmbeddingCache } from '@/lib/smart-router'

interface RouteCtx {
  params: Promise<{ id: string }>
}

const SCHEMA_CACHE_TTL_MS = 24 * 60 * 60 * 1000

export async function GET(req: NextRequest, ctx: RouteCtx) {
  try {
    enterWithOrg((await getActiveUser()).organizationId)
    const { id } = await ctx.params
    const refresh = new URL(req.url).searchParams.get('refresh') === '1'

    const integration = await db.integration.findFirst({ // nosemgrep
      where: { id },
      select: { id: true, name: true, provider: true, status: true, encryptedConfig: true, organizationId: true },
    })

    if (!integration) {
      return NextResponse.json(
        { ok: false, error: 'Integration not found.' },
        { status: 404 },
      )
    }

    let rows = await db.integrationSchema.findMany({ // nosemgrep
      where: { integrationId: id },
      orderBy: { tableName: 'asc' },
    })

    // ponytail: no cron — refresh on demand and surface staleness to the log.
    const oldestReflectedAt = rows[0]?.reflectedAt
    const stale = !!oldestReflectedAt && Date.now() - oldestReflectedAt.getTime() > SCHEMA_CACHE_TTL_MS
    if (stale) {
      console.log(`[schema] integration ${id} cached schema is older than 24h (reflectedAt ${oldestReflectedAt.toISOString()}) — call ?refresh=1 to re-reflect`)
    }

    if (refresh) {
      try {
        const connector = connectorRegistry.getConnector(
          id,
          integration.provider,
          decryptConfig(integration.encryptedConfig),
        )
        const tables = await connector.fetchSchema()
        // ponytail: preserve admin-edited descriptions across re-reflection.
        // The old flow deleteMany'd then createMany'd from scratch, silently
        // wiping every locked description + manualDescription flag — making
        // the "edit + lock" feature useless the moment an admin refreshed.
        const prev = new Map(rows.map((r) => [r.tableName, r]))
        await db.integrationSchema.deleteMany({ where: { integrationId: id } })
        await db.integrationSchema.createMany({
          data: tables.map((t) => {
            const old = prev.get(t.tableName)
            return {
              organizationId: integration.organizationId,
              integrationId: id,
              tableName: t.tableName,
              columns: JSON.stringify(t.columns ?? []),
              rowCount: t.rowCount ?? null,
              sampleRow: t.sampleRow ? JSON.stringify(t.sampleRow) : null,
              // Carry over a prior description only when an admin locked it;
              // auto-generated (non-manual) descriptions are regenerated by enrichment.
              description: old?.manualDescription ? old.description : null,
              manualDescription: old?.manualDescription ?? false,
            }
          }),
        })
        invalidateSourceEmbeddingCache()
        console.log(`[schema] integration ${id} re-reflected via ?refresh=1 (${tables.length} tables)`)
        rows = await db.integrationSchema.findMany({ // nosemgrep
          where: { integrationId: id },
          orderBy: { tableName: 'asc' },
        })
      } catch (e) {
        console.error(`[schema] refresh failed for integration ${id}:`, e)
        return NextResponse.json(
          { ok: false, error: 'Schema refresh failed. Check the connection and re-run the test.' },
          { status: 502 },
        )
      }
    }

    const tables = rows.map((r) => ({
      id: r.id,
      tableName: r.tableName,
      columns: safeParseColumns(r.columns),
      rowCount: r.rowCount,
      sampleRow: r.sampleRow ? safeParseJson(r.sampleRow) : undefined,
      description: r.description,
      manualDescription: r.manualDescription,
      reflectedAt: r.reflectedAt,
    }))

    return NextResponse.json({
      ok: true,
      data: {
        integrationId: integration.id,
        name: integration.name,
        provider: integration.provider,
        status: integration.status,
        tableCount: tables.length,
        tables,
      },
    })
  } catch (e) {
    return handleApiError(e, 'Failed to load integration schema.')
  }
}

interface SchemaPatchBody {
  table: string
  description: string | null
}

const SCHEMA_DESC_MAX = 500

/**
 * PATCH /api/integrations/[id]/schema
 * Edit (or reset) the natural-language description of a single table.
 *
 * - `description` is a non-null string (≤500 chars, trimmed) → persist it and set
 *   `manualDescription=true` so `enrichSchemaDescriptions` skips this row on
 *   re-enrichment (the admin's edit survives).
 * - `description: null` → clear `description` AND set `manualDescription=false`,
 *   marking the row for re-enrichment on the next refresh.
 *
 * Admin-only. Tenant-scoped: the integration is fetched via `findFirst` (the
 * prisma-tenant auto-scopes `IntegrationSchema`, but we scope the parent lookup
 * explicitly).
 */
export async function PATCH(req: NextRequest, ctx: RouteCtx) {
  try {
    const user = await getActiveUser()
    enterWithOrg(user.organizationId)
    requireRole(user, 'admin')
    const { id } = await ctx.params
    const body = (await req.json().catch(() => ({}))) as Partial<SchemaPatchBody>

    if (typeof body.table !== 'string' || !body.table.trim()) {
      return NextResponse.json(
        { ok: false, error: 'Field table (string) is required.' },
        { status: 400 },
      )
    }
    if (body.description !== null && typeof body.description !== 'string') {
      return NextResponse.json(
        { ok: false, error: 'Field description must be a string or null.' },
        { status: 400 },
      )
    }

    const integration = await db.integration.findFirst({ // nosemgrep
      where: { id },
      select: { id: true },
    })
    if (!integration) {
      return NextResponse.json(
        { ok: false, error: 'Integration not found.' },
        { status: 404 },
      )
    }

    const row = await db.integrationSchema.findFirst({ // nosemgrep
      where: { integrationId: id, tableName: body.table.trim() },
      select: { id: true, tableName: true, description: true, manualDescription: true },
    })
    if (!row) {
      return NextResponse.json(
        { ok: false, error: 'Schema row not found for this table.' },
        { status: 404 },
      )
    }

    let description: string | null
    let manualDescription: boolean
    if (body.description === null) {
      // Reset to auto: clear the description and the lock so re-enrichment regenerates it.
      description = null
      manualDescription = false
    } else {
      const trimmed = body.description!.trim()
      if (trimmed.length > SCHEMA_DESC_MAX) {
        return NextResponse.json(
          { ok: false, error: `description must be at most ${SCHEMA_DESC_MAX} characters.` },
          { status: 400 },
        )
      }
      description = trimmed
      manualDescription = true
    }

    const updated = await db.integrationSchema.update({
      where: { id: row.id },
      data: { description, manualDescription },
      select: { id: true, tableName: true, description: true, manualDescription: true },
    })

    await writeAudit({
      userId: user.userId,
      action: 'SCHEMA_DESC_UPDATE',
      severity: 'info',
      detail: {
        integrationId: id,
        tableName: row.tableName,
        manual: manualDescription,
        descriptionLength: description === null ? 0 : description.length,
      },
    })

    return NextResponse.json({ ok: true, schema: updated })
  } catch (e) {
    return handleApiError(e, 'Failed to update schema description.')
  }
}

function safeParseColumns(raw: string): Array<{ name: string; type: string; primaryKey?: boolean; notNull?: boolean; foreignKey?: string; distinctValues?: string[] }> {
  try {
    const parsed = JSON.parse(raw)
    if (Array.isArray(parsed)) {
      return parsed.map((c) => ({
        name: String(c?.name ?? ''),
        type: String(c?.type ?? ''),
        primaryKey: Boolean(c?.primaryKey) || undefined,
        notNull: Boolean(c?.notNull) || undefined,
        foreignKey: c?.foreignKey ? String(c.foreignKey) : undefined,
        distinctValues: Array.isArray(c?.distinctValues) ? c.distinctValues.map(String) : undefined,
      }))
    }
    return []
  } catch {
    return []
  }
}

function safeParseJson(raw: string): Record<string, unknown> | undefined {
  try {
    const parsed = JSON.parse(raw)
    if (typeof parsed === 'object' && parsed !== null && !Array.isArray(parsed)) return parsed
    return undefined
  } catch {
    return undefined
  }
}
