/**
 * Postgres demo data migration — creates Chinook, World, and Pagila demo
 * tables with Postgres-native DDL (quoted columns for case preservation),
 * then loads data from old SQLite custom.db.
 *
 * Usage: bun run scripts/migrate-demo-to-postgres.ts
 */
import { Database } from 'bun:sqlite'
import { db } from '../src/lib/db'

const SQLITE_PATH = 'db/custom.db'

// ── Postgres-native DDL with quoted column names (preserves case) ────
const DDL_STATEMENTS: string[] = [
  // Chinook (lowercase table names — Postgres default, LLM SQL works without quoting)
  `CREATE TABLE IF NOT EXISTS artist (artist_id INTEGER PRIMARY KEY, name VARCHAR(120))`,
  `CREATE TABLE IF NOT EXISTS album (album_id INTEGER PRIMARY KEY, title VARCHAR(160) NOT NULL, artist_id INTEGER)`,
  `CREATE TABLE IF NOT EXISTS customer (customer_id INTEGER PRIMARY KEY, first_name VARCHAR(40) NOT NULL, last_name VARCHAR(20) NOT NULL, company VARCHAR(80), address VARCHAR(70), city VARCHAR(40), state VARCHAR(40), country VARCHAR(40), postal_code VARCHAR(10), phone VARCHAR(24), fax VARCHAR(24), email VARCHAR(60) NOT NULL, support_rep_id INTEGER)`,
  `CREATE TABLE IF NOT EXISTS employee (employee_id INTEGER PRIMARY KEY, last_name VARCHAR(20) NOT NULL, first_name VARCHAR(20) NOT NULL, title VARCHAR(30), reports_to INTEGER, birth_date TIMESTAMP, hire_date TIMESTAMP, address VARCHAR(70), city VARCHAR(40), state VARCHAR(40), country VARCHAR(40), postal_code VARCHAR(10), phone VARCHAR(24), fax VARCHAR(24), email VARCHAR(60))`,
  `CREATE TABLE IF NOT EXISTS genre (genre_id INTEGER PRIMARY KEY, name VARCHAR(120))`,
  `CREATE TABLE IF NOT EXISTS mediatype (mediatype_id INTEGER PRIMARY KEY, name VARCHAR(120))`,
  `CREATE TABLE IF NOT EXISTS playlist (playlist_id INTEGER PRIMARY KEY, name VARCHAR(120))`,
  `CREATE TABLE IF NOT EXISTS playlisttrack (playlist_id INTEGER NOT NULL, track_id INTEGER NOT NULL, PRIMARY KEY (playlist_id, track_id))`,
  `CREATE TABLE IF NOT EXISTS track (track_id INTEGER PRIMARY KEY, name VARCHAR(200) NOT NULL, album_id INTEGER, mediatype_id INTEGER NOT NULL, genre_id INTEGER, composer VARCHAR(220), milliseconds INTEGER NOT NULL, bytes INTEGER, unit_price NUMERIC(10,2) NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS invoice (invoice_id INTEGER PRIMARY KEY, customer_id INTEGER NOT NULL, invoice_date TIMESTAMP NOT NULL, billing_address VARCHAR(70), billing_city VARCHAR(40), billing_state VARCHAR(40), billing_country VARCHAR(40), billing_postal_code VARCHAR(10), total NUMERIC(10,2) NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS invoiceline (invoiceline_id INTEGER PRIMARY KEY, invoice_id INTEGER NOT NULL, track_id INTEGER NOT NULL, unit_price NUMERIC(10,2) NOT NULL, quantity INTEGER NOT NULL)`,
  // World
  `CREATE TABLE IF NOT EXISTS "city" (id INTEGER PRIMARY KEY, name TEXT NOT NULL, countrycode TEXT NOT NULL, district TEXT NOT NULL, population INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "country" (code TEXT PRIMARY KEY, name TEXT NOT NULL, continent TEXT NOT NULL, region TEXT NOT NULL, surfacearea DOUBLE PRECISION NOT NULL, indepyear INTEGER, population INTEGER NOT NULL, lifeexpectancy DOUBLE PRECISION, gnp DOUBLE PRECISION, gnpold DOUBLE PRECISION, localname TEXT NOT NULL, governmentform TEXT NOT NULL, headofstate TEXT, capital INTEGER, code2 TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "countrylanguage" (countrycode TEXT NOT NULL, "language" TEXT NOT NULL, isofficial INTEGER NOT NULL, percentage DOUBLE PRECISION NOT NULL)`,
  // Pagila (lowercase columns — already lowercase in SQLite)
  `CREATE TABLE IF NOT EXISTS "pagila_actor" (actor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, first_name TEXT NOT NULL, last_name TEXT NOT NULL, last_update TIMESTAMP DEFAULT NOW() NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "pagila_category" (category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, last_update TIMESTAMP DEFAULT NOW() NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "pagila_film" (film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL, description TEXT, release_year INTEGER, language_id INTEGER NOT NULL, original_language_id INTEGER, rental_duration INTEGER DEFAULT 3 NOT NULL, rental_rate DOUBLE PRECISION DEFAULT 4.99 NOT NULL, length INTEGER, replacement_cost DOUBLE PRECISION DEFAULT 19.99 NOT NULL, rating TEXT DEFAULT 'G', last_update TIMESTAMP DEFAULT NOW() NOT NULL, special_features TEXT[], fulltext tsvector)`,
  `CREATE TABLE IF NOT EXISTS "pagila_film_actor" (actor_id INTEGER NOT NULL, film_id INTEGER NOT NULL, last_update TIMESTAMP DEFAULT NOW() NOT NULL, PRIMARY KEY (actor_id, film_id))`,
  `CREATE TABLE IF NOT EXISTS "pagila_film_category" (film_id INTEGER NOT NULL, category_id INTEGER NOT NULL, last_update TIMESTAMP DEFAULT NOW() NOT NULL, PRIMARY KEY (film_id, category_id))`,
  `CREATE TABLE IF NOT EXISTS "pagila_address" (address_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, address TEXT NOT NULL, address2 TEXT, district TEXT, city_id INTEGER NOT NULL, postal_code TEXT, phone TEXT, last_update TIMESTAMP DEFAULT NOW() NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "pagila_city" (city_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, city TEXT NOT NULL, country_id INTEGER NOT NULL, last_update TIMESTAMP DEFAULT NOW() NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "pagila_country" (country_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, country TEXT NOT NULL, last_update TIMESTAMP DEFAULT NOW() NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "pagila_customer" (customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, store_id INTEGER NOT NULL, first_name TEXT NOT NULL, last_name TEXT NOT NULL, email TEXT, address_id INTEGER NOT NULL, activebool INTEGER DEFAULT 1 NOT NULL, create_date TEXT DEFAULT (CURRENT_DATE)::text, last_update TIMESTAMP DEFAULT NOW(), active INTEGER)`,
  `CREATE TABLE IF NOT EXISTS "pagila_inventory" (inventory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, film_id INTEGER NOT NULL, store_id INTEGER NOT NULL, last_update TIMESTAMP DEFAULT NOW() NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "pagila_language" (language_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, last_update TIMESTAMP DEFAULT NOW() NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "pagila_payment" (payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id INTEGER NOT NULL, staff_id INTEGER NOT NULL, rental_id INTEGER NOT NULL, amount DOUBLE PRECISION NOT NULL, payment_date TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "pagila_rental" (rental_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, rental_date TEXT NOT NULL, inventory_id INTEGER NOT NULL, customer_id INTEGER NOT NULL, return_date TEXT, staff_id INTEGER NOT NULL, last_update TIMESTAMP DEFAULT NOW() NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "pagila_staff" (staff_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, first_name TEXT NOT NULL, last_name TEXT NOT NULL, address_id INTEGER NOT NULL, email TEXT, store_id INTEGER NOT NULL, active INTEGER DEFAULT 1 NOT NULL, username TEXT NOT NULL, password TEXT, last_update TIMESTAMP DEFAULT NOW() NOT NULL, picture BYTEA)`,
  `CREATE TABLE IF NOT EXISTS "pagila_store" (store_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, manager_staff_id INTEGER NOT NULL, address_id INTEGER NOT NULL, last_update TIMESTAMP DEFAULT NOW() NOT NULL)`,
]

function escapePgValue(v: unknown): string {
  if (v === null || v === undefined || v === '\\N') return 'NULL'
  if (typeof v === 'number') return String(v)
  if (typeof v === 'boolean') return v ? '1' : '0'
  const s = String(v).replace(/'/g, "''")
  return `'${s}'`
}

async function migrateTableData(
  sqlite: Database,
  pgTableName: string,
  sqliteTableName?: string,
  colMap?: Record<string, string>,
): Promise<number> {
  const srcTable = sqliteTableName ?? pgTableName
  const pgCount = await db.$queryRawUnsafe<{ c: number }[]>(`SELECT COUNT(*) as c FROM "${pgTableName}"`)
  if (Number(pgCount[0]?.c) > 0) {
    console.log(`  ${pgTableName}: ${pgCount[0].c} rows already in Postgres, skipping`)
    return Number(pgCount[0].c)
  }

  let rows: Record<string, unknown>[] = []
  try {
    rows = sqlite.query(`SELECT * FROM "${srcTable}"`).all() as Record<string, unknown>[]
  } catch {
    console.log(`  ${pgTableName}: not found in SQLite (${srcTable}), created empty table`)
    return 0
  }

  if (rows.length === 0) {
    console.log(`  ${pgTableName}: 0 rows in SQLite`)
    return 0
  }

  // Map column names if needed (e.g. ArtistId → artist_id)
  const srcCols = Object.keys(rows[0])
  const pgCols = colMap
    ? srcCols.map((c) => colMap[c] ?? c.toLowerCase())
    : srcCols.map((c) => c.toLowerCase())

  const BATCH = 100
  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH)
    const values = batch
      .map((row) => `(${srcCols.map((_, ci) => escapePgValue(row[srcCols[ci]])).join(', ')})`)
      .join(', ')
    const colList = pgCols.map((c) => `"${c}"`).join(', ')
    await db.$executeRawUnsafe(`INSERT INTO "${pgTableName}" (${colList}) VALUES ${values} ON CONFLICT DO NOTHING`)
  }

  console.log(`  ${pgTableName}: ${rows.length} rows migrated`)
  return rows.length
}

async function main() {
  console.log('╔══════════════════════════════════════════════════════════════╗')
  console.log('║  Demo Data Migration: SQLite → Postgres                      ║')
  console.log('╚══════════════════════════════════════════════════════════════╝')

  console.log('\n📋 Creating tables...')
  for (const ddl of DDL_STATEMENTS) {
    const tableName = ddl.match(/"(\w+)"/)?.[1] ?? 'unknown'
    try {
      await db.$executeRawUnsafe(ddl)
    } catch (e) {
      console.error(`  ERROR creating ${tableName}: ${e instanceof Error ? e.message : String(e)}`)
    }
  }
  console.log(`  ${DDL_STATEMENTS.length} tables processed`)

  console.log('\n📦 Loading data from SQLite...')
  const sqlite = new Database(SQLITE_PATH, { readonly: true })

  const dataTables = [
    'artist', 'album', 'customer', 'employee', 'genre', 'mediatype',
    'playlist', 'playlisttrack', 'track', 'invoice', 'invoiceline',
    'city', 'country', 'countrylanguage',
    'pagila_actor', 'pagila_category', 'pagila_film', 'pagila_film_actor', 'pagila_film_category',
    'pagila_address', 'pagila_city', 'pagila_country', 'pagila_customer',
    'pagila_inventory', 'pagila_language', 'pagila_payment', 'pagila_rental',
    'pagila_staff', 'pagila_store',
  ]

  const tableMap: Record<string, { sqliteName: string; colMap?: Record<string, string> }> = {
    artist: { sqliteName: 'Artist', colMap: { ArtistId: 'artist_id', Name: 'name' } },
    album: { sqliteName: 'Album', colMap: { AlbumId: 'album_id', Title: 'title', ArtistId: 'artist_id' } },
    customer: { sqliteName: 'Customer', colMap: { CustomerId: 'customer_id', FirstName: 'first_name', LastName: 'last_name', Company: 'company', Address: 'address', City: 'city', State: 'state', Country: 'country', PostalCode: 'postal_code', Phone: 'phone', Fax: 'fax', Email: 'email', SupportRepId: 'support_rep_id' } },
    employee: { sqliteName: 'Employee', colMap: { EmployeeId: 'employee_id', LastName: 'last_name', FirstName: 'first_name', Title: 'title', ReportsTo: 'reports_to', BirthDate: 'birth_date', HireDate: 'hire_date', Address: 'address', City: 'city', State: 'state', Country: 'country', PostalCode: 'postal_code', Phone: 'phone', Fax: 'fax', Email: 'email' } },
    genre: { sqliteName: 'Genre', colMap: { GenreId: 'genre_id', Name: 'name' } },
    mediatype: { sqliteName: 'MediaType', colMap: { MediaTypeId: 'mediatype_id', Name: 'name' } },
    playlist: { sqliteName: 'Playlist', colMap: { PlaylistId: 'playlist_id', Name: 'name' } },
    playlisttrack: { sqliteName: 'PlaylistTrack', colMap: { PlaylistId: 'playlist_id', TrackId: 'track_id' } },
    track: { sqliteName: 'Track', colMap: { TrackId: 'track_id', Name: 'name', AlbumId: 'album_id', MediaTypeId: 'mediatype_id', GenreId: 'genre_id', Composer: 'composer', Milliseconds: 'milliseconds', Bytes: 'bytes', UnitPrice: 'unit_price' } },
    invoice: { sqliteName: 'Invoice', colMap: { InvoiceId: 'invoice_id', CustomerId: 'customer_id', InvoiceDate: 'invoice_date', BillingAddress: 'billing_address', BillingCity: 'billing_city', BillingState: 'billing_state', BillingCountry: 'billing_country', BillingPostalCode: 'billing_postal_code', Total: 'total' } },
    invoiceline: { sqliteName: 'InvoiceLine', colMap: { InvoiceLineId: 'invoiceline_id', InvoiceId: 'invoice_id', TrackId: 'track_id', UnitPrice: 'unit_price', Quantity: 'quantity' } },
  }

  let totalRows = 0
  for (const table of dataTables) {
    try {
      const mapping = tableMap[table]
      totalRows += await migrateTableData(sqlite, table, mapping?.sqliteName, mapping?.colMap)
    } catch (e) {
      console.error(`  ${table}: ERROR — ${e instanceof Error ? e.message : String(e)}`)
    }
  }

  sqlite.close()
  console.log(`\n✅ Migration complete: ${totalRows} total rows`)

  console.log('\n🔍 Verification:')
  for (const table of dataTables) {
    try {
      const count = await db.$queryRawUnsafe<{ c: number }[]>(`SELECT COUNT(*) as c FROM "${table}"`)
      const n = Number(count[0]?.c ?? 0)
      console.log(`  ${table}: ${n} rows${n === 0 ? ' (empty)' : ''}`)
    } catch {
      console.log(`  ${table}: ERROR`)
    }
  }
}

main().catch(console.error).finally(() => db.$disconnect())
